Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "ubuntu-20" do |subconfig|
    subconfig.vm.box = "bento/ubuntu-20.04"
    subconfig.vm.network "public_network", bridge: "External Switch"
    subconfig.vm.hostname = "ubuntu-20"
    subconfig.vm.boot_timeout = 600
    subconfig.vm.communicator = "ssh"


    subconfig.vm.provider "hyperv" do |hyperv|
      hyperv.vmname = "ubuntu-20"
      hyperv.memory = 2048
      hyperv.cpus = 2
      hyperv.ip_address_timeout = 600
      hyperv.enable_virtualization_extensions = false
      hyperv.linked_clone = true
    end

  end

end
